theme: minima
title: GitHub Page!
author: Luke Schwarze
email: luke@ultimate9.co
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my GitHub page that I am learning to develop through GitHub's corses.
 
 I wanted to enter in a new line to see if this will be set as a new entry or inline with my intial sentence.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
